### PR TITLE
added caddy

### PR DESCRIPTION
**Pull request by midzer**
Hi all,
based on info from https://github.com/igrigorik/istlsfastyet.com/issues/145 I've added Caddy.

Cheers and have a nice weekend
midzer

### CODE REVIEW

**Comment by igrigorik** [comment]
> Note that Caddy's row will be nearly equivalent to Go's row except that Caddy's "OCSP Stapling" value will be Yes instead of Optional.

@mholt do we have Caddy documentation that we can point to for the various features, instead of Go? It's not entirely intuitive why the links are pointing at Go docs.

**Comment by mholt** [comment]
@igrigorik I agree, the links should point to Caddy's docs or maybe its code. The unique thing here is that most of these things are automatic in Caddy, rather than being something configurable, so finding a specific page to link to isn't obvious. (Maybe "automatic" is another option for cell text instead of just "yes"?)

I can add these points to a page of documentation -- either on the [Automatic HTTPS](https://caddyserver.com/docs/automatic-https) page or the [`tls` directive](https://caddyserver.com/docs/) page by the next release, and you can link to those instead maybe?

**Comment by igrigorik** [comment]
> I can add these points to a page of documentation -- either on the Automatic HTTPS page or the tls directive page by the next release, and you can link to those instead maybe?

That works!

**Comment by mholt** [comment]
Alright, you can link to https://caddyserver.com/docs/tls#summary -- it's a little redundant but this way it makes explicit what was otherwise only implicit.

**Comment by midzer** [comment]
:+1: @mholt 

Gonna push new commit soon.

**Comment by igrigorik** [comment]
@midzer @mholt thanks guys!

**Pull request merged**
