### PR TITLE
Fastly now supports dynamic record sizing.

### PR DESCRIPTION
**Pull request by WKHarmon**
Quick update -- we now support dynamic record sizing at Fastly.

### CODE REVIEW

**Comment by igrigorik** [comment]
\o/

**Comment by igrigorik** [comment]
@WKHarmon do you have a link to the announcement, blog post, or docs?

**Comment by WKHarmon** [comment]
@igrigorik Not yet.  We're quietly enabling TLS enhancements as they become available for now, and will likely make a consolidated announcement later this quarter when HTTP/2 enters limited availability.

**Comment by igrigorik** [comment]
"later this quarter when HTTP/2 enters limited availability" ... \o/, once more.

Sounds great.

**Pull request merged**
