### PR TITLE
Incapsula added Dynamic Record Sizing

### PR DESCRIPTION
**Pull request by ZigZagIL**
Already enabled globally.
https://incapsula.zendesk.com/hc/en-us/articles/235148027-Incapsula-TLS-SSL-Tech-Specs

### CODE REVIEW

**Comment by igrigorik** [comment]
Is there a blog post or an announcement we can link to?

**Comment by ZigZagIL** [comment]
we'll add one shortly

**Comment by ZigZagIL** [comment]
Ping'd doc owner again... wish ssllabs had a test :)
+OCSP Stapling also in roll-out...

**Comment by ZigZagIL** [comment]
https://incapsula.zendesk.com/hc/en-us/articles/235148027-Incapsula-TLS-SSL-Tech-Specs

**Comment by igrigorik** [comment]
\o/ ... can you update the PR with a link to that? :)

**Comment by igrigorik** [comment]
great stuff, thanks!

**Pull request merged**
