### PR TITLE
Akamai now supports OCSP stapling.

### LINKED ISSUE #58: OCSP stapling and SPDY on Akamai?
What is it needed to configure OCSP stapling and SPDY on Akamai?

The website I am working on consumes quite a few APIs that I know use Akamai, and I am quite positive these features are not in place, at least as per http://www.webpagetest.org/result/141205_KM_29b3d5e1a20891c168cc19b8633532a3/

Anyone has experience with getting it configured, so I can raise this to my colleagues who maintain those APIs?

### PR DESCRIPTION
**Pull request by rajiv**
closes #58.

### CODE REVIEW

**Comment by igrigorik** [comment]
@rajiv thanks! Any docs we can link to, to explain coverage and how to enable in various scenarios? From https://github.com/igrigorik/istlsfastyet.com/issues/58#issuecomment-287476518, it sounds like it's not a blanket "on for everyone".

**Comment by yoavweiss** [comment]
https://community.akamai.com/community/web-performance/blog/2017/10/27/certificate-provisioning-system-recommendations-and-best-practices

**Comment by yoavweiss** [comment]
There's also https://community.akamai.com/thread/4872-how-to-enable-ocsp-stapling for detailed explanations if needed.

**Comment by igrigorik** [comment]
👍 

@rajiv @yoavweiss can you update the PR with the link to the article?

**Comment by yoavweiss** [comment]
@igrigorik PTAL

**Pull request merged**
