### PR TITLE
Update index.html, added CDN77, changed order.

### PR DESCRIPTION
**Pull request by cdn77oskar**
Changed order under CDN & PaaS performance, now CDNs go from A to Z.
I saw that back in 2014 (Issue 47) someone has mentioned that they want us to be part of https://istlsfastyet.com, however nobody from our team followed up on that. So if you find it relevant, here are the values for our CDN & Paas performance.

### CODE REVIEW

**Comment by igrigorik** [comment]
Thanks. Do you have any links to docs or blog posts for how to enable HTTP/2 + related topics?

**Comment by cdn77oskar** [comment]
Hi,

we offer http/2 by default, once you log in you get to choose between http/2 and http/1.1 cdn resource.

Session identifiers, Session tickets and Forward secrecy can be all seen here:
https://www.ssllabs.com/ssltest/analyze.html?d=1906714720.rsc.cdn77.org&hideResults=on

Other than this, we came up with HTTP 1.1 vs H/2 demo couple of months ago (http2demo.io), where you can check in Google Dev tools that images loaded from the second server are loaded using h2. 

Is that what you had in mind? Is it sufficient?

**Comment by igrigorik** [comment]
Ideally I'm looking for user visible docs.. something folks can click on right from istlsfastyet.com to read about supported features and how to enable them.

**Comment by cdn77oskar** [comment]
For instance - https://www.cdn77.com/http2

Does it have to be available available for every parameter?
Would one document, which sums it all up be sufficient?

**Comment by igrigorik** [comment]
@cdn77oskar thanks, that http2 link looks great. A single page is good, I'm just looking for something that a developer can scan and confirm that these features are supported.

**Comment by igrigorik** [comment]
Closing, CDN77 is now on the list.

**Pull request closed without merging**
