### PR TITLE
Incapsula added HTTP/2 support

### PR DESCRIPTION
**Pull request by ZigZagIL**
https://www.incapsula.com/blog/http2-is-here-what-you-need-to-know.html
https://http2.incapsula.com

### CODE REVIEW

**Comment by igrigorik** [comment]
Nice, thanks for the update! Do you mind updating the pull to link to the http/2 announcement?

**Comment by ZigZagIL** [comment]
sure

**Comment by ZigZagIL** [comment]
?

**Comment by igrigorik** [comment]
Sorry, missed the update. Looks good, thanks!

**Pull request merged**
