### PR TITLE
add BelugaCDN.com

### PR DESCRIPTION
**Pull request by AdamJacobMuller**
Hi Ilya,

I'm from BelugaCDN.com and we'd like to add ourselves to your site.

Thanks and let me know if you have any questions,

-Adam

### CODE REVIEW

**Comment by igrigorik** [comment]
Hi Adam. Thanks for putting this together!

One nitpick: do you have any docs or FAQ's that we can link to, for each of the features? E.g. what the user has to do to enable http/2 and all the various features?

**Comment by AdamJacobMuller** [comment]
Hi Ilya,

All the features there are implicitly enabled when you enable SSL.

We are in process of some additional documentation, but, it does not exist just yet, I can open an additional pull request later to add it as soon as we have it.

**Comment by igrigorik** [comment]
@AdamJacobMuller can you update this pull once you have the docs in place? I'd prefer to wait until we have that.

**Comment by igrigorik** [comment]
@AdamJacobMuller any luck on the docs? :)

**Comment by AdamJacobMuller** [comment]
Hi Ilya,

We're working on putting that up at the same time as a few other new features (full API release), should go live in the next two weeks approximately.

We can close this and I'll make a new one later or just leave it open until then, I'm fine with either.

-Adam

**Comment by igrigorik** [comment]
Great, thanks for the update. Let's keep this open and land it once you guys are ready.

**Comment by AdamJacobMuller** [comment]
Hi @igrigorik,

I added links to the specific documentation regarding our SSL configuration, if you have any other questions let me know.

Thanks,
-Adam

**Comment by igrigorik** [comment]
awesome, thank you 👍

**Pull request merged**
